#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../custom/lib", "$FindBin::Bin/../lib", "$FindBin::Bin/../lib/cpan" }
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('Botcave');
